version: '2.0'

services:
  springboot:
    build: .   
    container_name: springboot
    ports:
      - 8085:8085
    links:
      - neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    