version: '3.1'

services:
  springboot:
    build: .    
    restart: always
    container_name: springboot
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - neo4j
  
  neo4j:
    image: neo4j:3.2
    ports:
      - "7474:7474"
      - "7687:7687"


      

