version: '3'
services:
  java:
    container_name: openjdk8
    image: openjdk:8    
    volumes:
    - .:/app/java 
  neo4j:
    image: neo4j:3.2
    ports:
    - "7474:7474"
    - "7687:7687"
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - java
      - neo4j
      

