version: '3.0'

services:
  springboot:
    build: .    
    restart: always
    container_name: springboot
    ports:
      - 8085:8085
    links:
      - neo4j
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:3.2
    ports:
      - "7474:7474"
      - "7687:7687"


      

